//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakim
    {
        public int ID { get; set; }
        public string BakimAdi { get; set; }
        public Nullable<System.DateTime> BakimTarihi { get; set; }
        public string BakimYapanPersonel { get; set; }
        public string Periyot { get; set; }
    }
}
