//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisansDetay
    {
        public int ID { get; set; }
        public string ProgramAd { get; set; }
        public System.DateTime ProgramTarih { get; set; }
        public Nullable<decimal> ProgramFiyat { get; set; }
        public Nullable<System.DateTime> ProgramBitisTarihi { get; set; }
    }
}
