//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lisans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lisans()
        {
            this.LisansDetay = new HashSet<LisansDetay>();
        }
    
        public int ID { get; set; }
        public string ProgramAdi { get; set; }
        public Nullable<int> Adet { get; set; }
        public string FirmaAdi { get; set; }
        public string SabitTelefon { get; set; }
        public string Gsm { get; set; }
        public string Mail { get; set; }
        public System.DateTime AlimTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public System.DateTime YenilemeTarihi { get; set; }
        public Nullable<decimal> AlisFiyati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LisansDetay> LisansDetay { get; set; }
    }
}
