//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int ID { get; set; }
        public int BakimID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mail { get; set; }
    
        public virtual Bakim Bakim { get; set; }
    }
}
