//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int ID { get; set; }
        public string İsAdi { get; set; }
        public string BakimPeriyodu { get; set; }
        public string FirmaAdi { get; set; }
        public string SabitTelefon { get; set; }
        public string DestekPersonelAdSoyad { get; set; }
        public string Gsm { get; set; }
        public string Mail { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public string BakimveAciklamalar { get; set; }
    }
}
