//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class takipDbEntities : DbContext
    {
        public takipDbEntities()
            : base("name=takipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakim> Bakim { get; set; }
        public virtual DbSet<BakimAciklama> BakimAciklama { get; set; }
        public virtual DbSet<BakimMailPeriyodu> BakimMailPeriyodu { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Lisans> Lisans { get; set; }
        public virtual DbSet<LisansDetay> LisansDetay { get; set; }
        public virtual DbSet<LisansMailPeriyodu> LisansMailPeriyodu { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yedekleme> Yedekleme { get; set; }
        public virtual DbSet<YedeklemeMailPeriyodu> YedeklemeMailPeriyodu { get; set; }
    }
}
