//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yedekleme
    {
        public int ID { get; set; }
        public string YedeklemeTipiPlatformu { get; set; }
        public string YedeklemePeriyodu { get; set; }
        public string YedeklemePlaniAdi { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> SonYedeklemeTarihi { get; set; }
        public string KontrolEdenPersonel { get; set; }
        public Nullable<System.DateTime> SonKontrolTarihi { get; set; }
    }
}
